version: '3'

services:
  app:
    image: 'c2876f6e172c2067e9510f4ff6488abeba04774341e059811c7c5a0a72a87d9d'
    container_name: app
    ports:
      - '8080:8080'
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root


